version: '3.8'

services:
  business-platform:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: business-platform
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    networks:
      - business-platform-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  business-platform-network:
    driver: bridge
